name: Build an test
on: [push]

jobs:
    build-backend:
        runs-on: ubuntu-latest
        name: Build backend
        defaults:
          run:
            working-directory: backend
        steps:
          - uses: actions/checkout@v4
            name: Checkout backend
          - uses: actions/setup-dotnet@v4
            name: Setup dotnet
            with:
                dotnet-version: 9.0.300
          - name: Build backend
            run: dotnet build --configuration Release src/API
            
    build-frontend:
        runs-on: ubuntu-latest
        name: Build frontend
        defaults:
          run:
            working-directory: frontend
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            name: Build frontend
            with:
                node-version: '20.x'
          - run: npm install
          - run: npm run build

    test-backend:
      runs-on: ubuntu-latest
      name: Test backend
      defaults:
        run:
          working-directory: backend
      steps:
          - name: Checkout backend
            uses: actions/checkout@v5
          - name: Setup .NET
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: 9.0.300
          - name: Run backend tests
            run: dotnet test src/API
    
    test-frontend:
        runs-on: ubuntu-latest
        name: Test frontend
        defaults:
          run:
            working-directory: frontend
        
        steps:
            - uses: actions/checkout@v5
              name: Checkout frontend
            - uses: actions/setup-node@v4
              name: Setup node
              with:
                node-version: '20.x'
            - name: Test frontend
              run: |
                npm install
                npm run test